### ISSUE TITLE
Why gradient?

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#1]
Here the comment speaks about a gradient?
Do we use one?

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent.h#L60

**Comment by rainazakir** [comment]
Corrected in commit https://github.com/rainazakir/argos3-kilogrid/commit/ccfb34c7e94d215d12ffe86b075e18fa30b17357
