### ISSUE TITLE
You can use enum to indicate the meaning of the states with word. It can simplify the code and reduce bugs

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#11]
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L413

**Comment by rainazakir** [comment]
Changed in 3664c5e45b615b62e2fcdce39193481c046a7c20
