### ISSUE TITLE
kilogrid sends commitment = 3 and the robot sets its commitment to 2

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#12]
I don't know if this was wanted or if it is a bug, however, it does not make much sense and can easily introduce bugs

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L458

**Comment by rainazakir** [comment]
It's not a bug but definitely can be improved together with #18 as they are interlinked

**Comment by rainazakir** [comment]
Changed in b15f22b25e534ec09322e084446cbbde60056089 also check #18
