### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#13]
`if (MODEL == 1){ `
or
`if (MODEL == 0){ `
seems to do the same identical thing.

Probably the code can be much improved.

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L438

**Comment by joefresna** [comment]
I revise my statement, there is a difference, only the CROSS INHIBITION model checks if the robot is against a wall, the voter model doesn't. 
It is unclear why only of the two is doing so

**Comment by rainazakir** [comment]
I moved the `check_if_against_a_wall()` outside so it gets executed before entering of the conditional statements 146db995fb20fdec99b2633fb64f7e6162049646

**Comment by joefresna** [comment]
and then what's the `if` needed for?

**Comment by rainazakir** [comment]
Yeah, there is no need for the condition. I removed it in ae80b79dcd5c90b6c28b70da9b90c601a79b1b7c
