### ISSUE TITLE
It would be better to define the average time in exploration state as number of ticks

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#14]
now the average time is 0.0003 which does not make sense... 

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L62

**Comment by rainazakir** [comment]
The Valentini model uses exponentially distributed periods of time for dissemination and exploration. However, I think putting this in ticks won't make a lot of difference?

**Comment by joefresna** [comment]
I think Valentini in his paper says that the average exploration time is, I don't know, for example, 300 ticks, that is drawn from an exponential function. (Possibly I'm wrong.)
In your case, you need to write that your average time is drawn from an exponential with parameter 0.0003. Or alternatively that it has an average time of 3333.33 ticks...
I would work and think in terms of average exploration time, like (I think) Valentini did, not in terms of the number that you put in your exponential. You will need to motivate your choices and I find it hard to motivate the choice = of 0.0003, instead I could better motivate the choice of a give average time.

**Comment by rainazakir** [comment]
Can you have a look at b4ac9ca1dcef399b434f399d23e866f88584a7ef or do you think its better I set in the parameters:
```
double qnorm = 3333.33; //***--> time to be in exploration state--> fixed
double quncommitted = 200; // time to stay in dissemination for uncommitted agents
```

and then in code:
`timer =  ran_expo(1/quncommitted); //set time to be in dissem state but will not talk`
or 
`timer =  ran_expo(1/qnorm); //set time to be in dissem state but will not talk`

**Comment by joefresna** [comment]
I think this is better
```
double qnorm = 3333.33; //***--> time to be in exploration state--> fixed
double quncommitted = 200; // time to stay in dissemination for uncommitted agents
```

Possibly the average exploration time, rather than `qnorm` could be called `avg_exploration_time`
and `quncommitted` as `avg_uncommitted_time`

As mentioned before, we will need to justify the use of parameters, an 3333.33 is quite a strange choice. Any reason for that? 
If the target was to have average exploration for 100 seconds, then you need to decide if we use as convention 32 or 33 ticks per second (or any other similar value), and therefore it would make sense using 3200 or 3300.

Please let me know if something is unclear or I misunderstood something.

**Comment by rainazakir** [comment]
I wanted to have a mean exploration time somewhere around 3200-3300 and cause I was thinking solely in terms of exponential parameter, I wanted it to be 0.0003 (when I tested some varying exploration times) which is 1/3333.3. I think we can just put it as 3300 which definitely makes more sense. cf092e0b69ad22e19fb0d8e5edc6989b3d3346d2
