### ISSUE TITLE
Uclear use of `random_walk()` function

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#15]
The `random_walk()` function is called at the beginning and at the end of the function. Unclear why.

Also, not clear why the motion of the robot should change depending on the state in which it is. The robot should ALWAYS do a random walk regardless of the exploration, dissemination, or polling state.

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L543

**Comment by rainazakir** [comment]
Removed repetitive random_walk() in 31759de84f71a829ee62d024065f1a8373da5dbc. I would also like you to cross-check question in  #9
