### ISSUE TITLE
probably unnecessary

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#16]
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L619

**Comment by rainazakir** [comment]
Removed in 5d842461e547e1ceffcec9d94ee523d83ce87dab

**Comment by joefresna** [comment]
I don't think this change was anyway very important... however, you say 
Removed in https://github.com/rainazakir/argos3-kilogrid/commit/5d842461e547e1ceffcec9d94ee523d83ce87dab
but then it has been reintroduced in 
https://github.com/rainazakir/argos3-kilogrid/commit/b4ac9ca1dcef399b434f399d23e866f88584a7ef

**Comment by rainazakir** [comment]
Thanks for spotting this, removed forever in 0e8dc81adaa7a80d05ffcf71c41b1bdb8a998a1a
