### ISSUE TITLE
Code should be cleaned

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#17]
Why do you do this if you never use it?

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L697

**Comment by joefresna** [comment]
and this?
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L696

**Comment by rainazakir** [comment]
Resolved in 05f9cf854d942e9e4b88542a8bebf86211960b2a

**Comment by joefresna** [comment]
Great! 
I indicated just three (randomly picked) variables, but it may be possible there are many other variables not used in your code... I see you only removed those three... possibly they are all.

**Comment by rainazakir** [comment]
I did remove others in #4
