### ISSUE TITLE
Cleaner code reduces bugs

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#18]
Wouldn't be better to:
* use same opinion in robots and kilogird
* use another data value to indicate the wall or not the wall
?

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L714

**Comment by rainazakir** [comment]
I used another data value to receive message from Kilogrid about whether its wall or not, I have updated it in b15f22b25e534ec09322e084446cbbde60056089 and 8b9e85b2f09102a4b43bc470b2c37750e0ffd006 . Do you think I should use enums here?

**Comment by joefresna** [comment]
enums could be tricky to be matched between kilogrid and robot... but maybe using the shared header file it can be done without the risk the two enums are different in robot and grid
