### ISSUE TITLE
is this necessary?

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#19]
https://github.com/rainazakir/argos3-kilogrid/blob/b5d74efa01500872b6b49d98748f95064df7a29f/ARGoS_simulation/behaviours/agent_main.c#L864

**Comment by rainazakir** [comment]
I would want to keep this, it was just to check things visually when running real bot experiments but doesn't really matter in simulation

**Comment by joefresna** [comment]
I agree it could be useful for real robots, but then why not using `#ifndef SIMULATION` ?
