### ISSUE TITLE
Why does the robot need to know the SWARMSIZE?

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#3]
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L49

**Comment by rainazakir** [comment]
It used to know this when the polling was based on getting multiple opinions and storing them in an array to be randomly picked. Now it does not need it and removed this is in https://github.com/rainazakir/argos3-kilogrid/commit/daf75204296c543f539437d4bf92c4cb4b21bb49
