### ISSUE TITLE
Delete variables that are never used

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#4]
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L90

**Comment by rainazakir** [comment]
Removed this and other unused variables in d6fd44198ca634964795bcabe3cac2160f0ae697 and 05f9cf854d942e9e4b88542a8bebf86211960b2a
