### ISSUE TITLE
I'm not sure the delay function works properly in ARGoS

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#5]
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L241

It may be better to use a function based on dedicated states that are run for a certain amount of kilo_ticks (i.e. repeated a few loops).

However, if you find that ARGoS manages ok the delay and you get the desired behaviour, then you can keep it.
It would be good if you show me which tests you do for checking the delay function, so we can be sure it is handled properly.

**Comment by rainazakir** [comment]
Changed in b5d74efa01500872b6b49d98748f95064df7a29f
