### ISSUE TITLE
Why the value 0.05 is added to RAND_MAX?

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#6]
https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L269

**Comment by rainazakir** [comment]
This is a bug and the random number to calculate should not be [0,0.05) but [0,1) based on the definition of exponential distribution. I have fixed this in 005b7dd622aac9f54ef0422f6be69c698c04d060

**Comment by rainazakir** [comment]
The update closes #6

**Comment by joefresna** [comment]
not sure it now does what you wanted...
`rand()` gives you a number between 0 and `RAND_MAX` https://www.cplusplus.com/reference/cstdlib/rand/

then you should divide it by `RAND_MAX` without the `+ 1.0`. 
You may need to cast `RAND_MAX` to `double` though.

right?

**Comment by rainazakir** [comment]
`rand()/(RAND_MAX + 1.0)` will generate a floating-point random number between [0, 1.0). 

The the `1.0` will make the denominator assume its floating point type, so no need to cast. I checked this by printing out the value of `u`:
https://github.com/rainazakir/argos3-kilogrid/blob/ae80b79dcd5c90b6c28b70da9b90c601a79b1b7c/ARGoS_simulation/behaviours/agent_main.c#L268


If I use `(double)rand() / (double)RAND_MAX`, then it will generate number between [0,1]

**Comment by joefresna** [comment]
ah ok, thanks for clarifying. I did not consider the distinction between [0,1) and [0,1]. 
It now makes sense as we do not want 1.
