### ISSUE TITLE
the code (((float)1/1)*1300) does not look great

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#7]
this: `(((float)1/1)*1300)` could be written as `1300.0`.
Also, I believe 1300.0 is a parameter that should be specified as one of the parameters in the top of the file

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L327

**Comment by joefresna** [comment]
i.e. when you specify the exploration and dissemination time
 https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L62

**Comment by rainazakir** [comment]
Added in f7bd12596b1cdf3ce60f4698e5117d7fea19d3ef

**Comment by joefresna** [comment]
I am still wondering the utility of `1/1`

**Comment by rainazakir** [comment]
There is absolutely no utility. Removed in f5c27a1b59e19a4fb28c694eaf1e1ce0833ddf50
