### ISSUE TITLE
Why not doing random_walk in dissemination state?

### ISSUE THREAD

**Issue by joefresna** [rainazakir/argos3-kilogrid#9]
`random_walk()` is called only when the robot enters the exploration state, not when it goes into dissemination

https://github.com/rainazakir/argos3-kilogrid/blob/5b966a9dd2a49a1097fc2cbbf2f1d72ec9c2ce94/ARGoS_simulation/behaviours/agent_main.c#L410

**Comment by rainazakir** [comment]
Its within dissem function: 
https://github.com/rainazakir/argos3-kilogrid/blob/31759de84f71a829ee62d024065f1a8373da5dbc/ARGoS_simulation/behaviours/agent_main.c#L541

 but I guess it should be before the dissem function is called?

**Comment by joefresna** [comment]
Probably it's better to handle the robot motion outside the states that manage the opinions as the two things are not linked to each other.

In the `loop()` function you can have 
```
if (hit_wall) {
  do_something
} else {
  random_walk();
}
```

**Comment by rainazakir** [comment]
I tried to remove the unnecessary random_walks from the states and reduce its repetition, I have placed the check for hitwall and random_walk in loop 22044700adc82f3aed9a2ea922053b8db0211e7a

**Comment by rainazakir** [comment]
The code is changed and problem is fixed in b5d74efa01500872b6b49d98748f95064df7a29f
